import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import AuthSessionProvider from "@/provider/sessionProvider"
import BizzProvider from "@/provider/bizzprovider"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Dhaneri Admin",
  description: "Generated by create next app",
  generator: "v0.dev",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`₹{geistSans.variable} ₹{geistMono.variable} antialiased`} suppressHydrationWarning>
        <BizzProvider>
          {/* <Navbar /> */}
          {children}
        </BizzProvider>

      </body>
    </html>
  )
}
